spring.application.name: config-client
server.port: 8881
spring:
  datasource:
    url: jdbc:oracle:thin:@10.150.27.233:1521:PRODxxxx1111
    username: TRFF_APP
    password: ehl1234
    driver-class-name: oracle.jdbc.driver.OracleDriver
