server.port: 9999
spring.profiles.active: native
spring.cloud.config.server.native.searchLocations: classpath:/config-repo
#spring.cloud.config.server.native.searchLocations: file:F:\\optFile\\workspaceAll\\configServer\\src\\main\\resources\\config-repo